# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Required by RNFirebase
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth', '~> 5.3.0'
pod 'Firebase/Database', '~> 5.3.0'
pod 'Firebase/Firestore', '~> 5.3.0'
pod 'Firebase/Storage', '~> 5.3.0'
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

target 'Tutu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tutu

  target 'Tutu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'TutuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

